### ISSUE TITLE
[Insight] Text files should end with a newline character - in app/config/config_test.yml, line 27

### ISSUE THREAD

**Issue by natinho68** [natinho68/ToDoList#43]
**[in app/config/config_test.yml, line 27](https://github.com/natinho68/ToDoList/blob/d0c46877700cc3c45acfe8e6fbb5f2b3cc533257/app/config/config_test.yml#L27)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```

## add this to simulate authentication for tests
security:
    firewalls:
        main:
            http_basic: ~
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/8feade4b-1726-4966-a0ef-c0e3303920ea/analyses/3)_
